### ISSUE TITLE
Unexpected error: Invalid character in name 

### ISSUE THREAD

**Issue by python-coding-404** [redwerks/mediawiki-shorturl-builder#12]
I just tried to just use the option for it and it gave me an error
- [ ] I have checked for related issues

## Context
<details>
<summary>Details</summary>
<pre>
Invalid character in name
----
Error: Invalid character in name
    at e.value (https://shorturls.redwerks.org/static/js/main.98db52a4.js:2:1323185)
    at e.value (https://shorturls.redwerks.org/static/js/main.98db52a4.js:2:1319930)
    at new d (https://shorturls.redwerks.org/static/js/main.98db52a4.js:2:1294137)
    at l.value (https://shorturls.redwerks.org/static/js/main.98db52a4.js:2:1303762)
    at l.value (https://shorturls.redwerks.org/static/js/main.98db52a4.js:2:1302492)
    at l.value (https://shorturls.redwerks.org/static/js/main.98db52a4.js:2:1301748)
    at e.exports.create (https://shorturls.redwerks.org/static/js/main.98db52a4.js:2:1332952)
    at m (https://shorturls.redwerks.org/static/js/main.98db52a4.js:2:1039678)
    at https://shorturls.redwerks.org/static/js/main.98db52a4.js:2:1652899
    at Object.addServerInstructions (https://shorturls.redwerks.org/static/js/main.98db52a4.js:2:1652955)
</pre>
</details>

**Comment by dantman** [comment]
Could you share what url or settings you chose?

**Comment by python-coding-404** [comment]
IIS 7.0+

**Comment by python-coding-404** [comment]
@dantman  IIS 7.0+

**Comment by dantman** [comment]
Ok, there does appear to be something wrong with the IIS option.

**Comment by python-coding-404** [comment]
Unexpected error
An unexpected error has occurred with the following message:

Invalid character in name
Details
Invalid character in name
----
Error: Invalid character in name
    at e.value (https://shorturls.redwerks.org/static/js/main.98db52a4.js:2:1323185)
    at e.value (https://shorturls.redwerks.org/static/js/main.98db52a4.js:2:1319930)
    at new d (https://shorturls.redwerks.org/static/js/main.98db52a4.js:2:1294137)
    at l.value (https://shorturls.redwerks.org/static/js/main.98db52a4.js:2:1303762)
    at l.value (https://shorturls.redwerks.org/static/js/main.98db52a4.js:2:1302492)
    at l.value (https://shorturls.redwerks.org/static/js/main.98db52a4.js:2:1301748)
    at e.exports.create (https://shorturls.redwerks.org/static/js/main.98db52a4.js:2:1332952)
    at m (https://shorturls.redwerks.org/static/js/main.98db52a4.js:2:1039678)
    at https://shorturls.redwerks.org/static/js/main.98db52a4.js:2:1652899
    at Object.addServerInstructions (https://shorturls.redwerks.org/static/js/main.98db52a4.js:2:1652955)

It is still happening
